service: notification-fuzzer

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  apiKeys:
    - nf-${self:custom.stage}-key
  usagePlan:
    quota:
      limit: 10000
      period: MONTH
    throttle:
      burstLimit: 10
      rateLimit: 3

functions:
  follow:
    handler: handler.follow
    events:
      - schedule: rate(47 minutes)
    timeout: 60
  speak:
    handler: handler.speak
    events:
      - schedule: rate(109 minutes)
    timeout: 60
  generate:
    handler: handler.generate
    events:
      - http:
          path: generate
          method: get
          private: true
          cors: true
    timeout: 60


custom:
  stage: ${opt:stage, self:provider.stage}
