service: notification-fuzzer

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1

functions:
  follow:
    handler: handler.follow
    events:
      - schedule: rate(47 minutes)
    timeout: 60
  speak:
    handler: handler.speak
    events:
      - schedule: rate(109 minutes)
    timeout: 60
